name: Build
on:
  push:
    branches:
      - android

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: ./
          buildozer_version: stable

      - name: UploadArtifacts
        uses: actions/upload-artifact@v4
        with:
          name: Android
          path: ${{ steps.buildozer.outputs.filename }}
